name: Release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10
        
    - name: Setup JAVA
      uses: actions/setup-java@v5
      with:
        distribution: 'microsoft'
        java-version: '25'
        check-latest: true
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v4

    - name: Install .NET workflows
      run: dotnet workload restore
      
    - name: Build
      run: >
        dotnet build
        -t:InstallAndroidDependencies
        -p:AcceptAndroidSdkLicenses=True
      
    - name: Publish
      env:
        KEY_PASS: ${{ secrets.KEY_PASS }}
      run: >
        dotnet publish
        -o ./apks
        -c Release
        -p:AndroidKeyStore=True
        -p:AndroidSigningKeyStore="arise"
        -p:AndroidSigningStorePass="$KEY_PASS"
        -p:AndroidSigningKeyAlias="arise"
        -p:AndroidSigningKeyPass="$KEY_PASS"
    
    - name: Upload APK
      uses: actions/upload-artifact@v7
      with:
        path: ./apks
        if-no-files-found: error